USE RendimientoRugby;
CREATE TABLE USUARIO (
    IDUsuario BIGINT PRIMARY KEY,
    NombreUsuario VARCHAR(100) NOT NULL,
    Email VARCHAR(150) NOT NULL UNIQUE,
    IDRol BIGINT NOT NULL,
    FOREIGN KEY (IDRol) REFERENCES ROL(IDRol)
);
